### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by jejsus** [ndevenish/Blender_ioEDM#3]
Hello, when I tried to install the plugin it gave me the error you can see on screenshot http://prntscr.com/dpbib8 .

**Comment by ndevenish** [comment]
I seem to be able to replicate this by switching it off and on. It's fixed on mine in 05e817.. Give https://github.com/ndevenish/Blender_ioEDM/releases/tag/v0.2.1 a go and let me know if that fixes it (Or, if you were using the latest code manually, the fix is in there too)

**Comment by jejsus** [comment]
Hi, thanks for quick reply. This is what version 0.2.1 tells me http://prntscr.com/dpeevg
It also didn't work for me in 0.2.0 version by manually changing the script.

**Comment by jejsus** [comment]
Ok, I've just updated Blender from 2.76b to 2.78a and I've successfully enabled EDM addon, but can't find EDM export option.

**Comment by jejsus** [comment]
A little update - I've installed the addon on the second computer this time I first updated Blender version to the latest and then installed EDM plugin. There it shows import/export option. I assume that the reason was I tried to install on 1.76b version before updating to 1.78a. Thank you for a great and long awaited solution for Blender/DCS. Happy upcoming New Year.

**Comment by ndevenish** [comment]
Ah - I hadn't tested on older Blender versions, and assumed that it hadn't changed dramatically in recent versions. Unless there are good reasons to explicitly support older blender versions, I'm reluctant to spend the time looking into it.

Also, I just reproduced the missing import/export buttons and so that should be fixed in cadf50d06fcc7c0b0fe19dcf093189ddbe1b54f7, so unless it comes back I'm now closing this.

Thanks for the reports!
